export interface ActionResult {
  success: boolean;
  message: string;
}

const githubApiBaseUrl = "https://api.github.com";

function githubHeaders(token: string): HeadersInit {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28"
  };

  if (token.trim()) {
    headers.Authorization = `Bearer ${token}`;
  }

  return headers;
}

async function responseMessage(response: Response): Promise<string> {
  const text = await response.text();

  try {
    const payload = JSON.parse(text) as { message?: string };
    return payload.message || `GitHub ${response.status}`;
  } catch {
    return `GitHub ${response.status}: ${text}`;
  }
}

export async function mergePR(repo: string, prNumber: number, title: string, token: string): Promise<ActionResult> {
  try {
    const response = await fetch(`${githubApiBaseUrl}/repos/${repo}/pulls/${prNumber}/merge`, {
      method: "PUT",
      headers: {
        ...githubHeaders(token),
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        merge_method: "squash",
        commit_title: title
      })
    });

    if (!response.ok) {
      return { success: false, message: await responseMessage(response) };
    }

    return { success: true, message: "Mergeado" };
  } catch (error) {
    return { success: false, message: error instanceof Error ? error.message : String(error) };
  }
}

export async function createIssue(
  repo: string,
  title: string,
  body: string,
  labels: string[],
  token: string
): Promise<ActionResult> {
  try {
    const response = await fetch(`${githubApiBaseUrl}/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        ...githubHeaders(token),
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ title, body, labels })
    });

    if (!response.ok) {
      return { success: false, message: await responseMessage(response) };
    }

    const payload = (await response.json()) as { number?: number };
    return { success: true, message: payload.number ? `Issue #${payload.number} creada` : "Issue creada" };
  } catch (error) {
    return { success: false, message: error instanceof Error ? error.message : String(error) };
  }
}

export async function pushWorkflow(
  repo: string,
  defaultBranch: string,
  workflowYaml: string,
  token: string
): Promise<ActionResult> {
  try {
    const existing = await fetch(`${githubApiBaseUrl}/repos/${repo}/contents/.github/workflows/ci.yml`, {
      headers: githubHeaders(token)
    });

    if (existing.ok || existing.status === 422) {
      return { success: false, message: "El workflow ya existe" };
    }

    if (existing.status !== 404) {
      return { success: false, message: await responseMessage(existing) };
    }

    const response = await fetch(`${githubApiBaseUrl}/repos/${repo}/contents/.github/workflows/ci.yml`, {
      method: "PUT",
      headers: {
        ...githubHeaders(token),
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        message: "ci: add GitHub Actions CI workflow\n\nAutomatically generated by github-scanner",
        content: Buffer.from(workflowYaml).toString("base64"),
        branch: defaultBranch
      })
    });

    if (!response.ok) {
      if (response.status === 422) {
        return { success: false, message: "El workflow ya existe" };
      }

      return { success: false, message: await responseMessage(response) };
    }

    return { success: true, message: "Pusheado" };
  } catch (error) {
    return { success: false, message: error instanceof Error ? error.message : String(error) };
  }
}
